### ISSUE TITLE
Auto type GVL

### ISSUE THREAD

**Issue by fenahurtado** [DEMCON/plcdoc#24]
Is it possible to auto type the variables defined in a TcGVL file? How can I do it?

**Comment by RobertoRoos** [comment]
Thanks for your question! No, I don't think GVLs are implemented yet. Though they should absolutely be covered! The logic is pretty much present already, I'll get on it when I can. (Though that should be a couple of weeks as I'm currently at the beach on holiday.)

Of course we'd welcome PRs too.

**Comment by RobertoRoos** [comment]
See https://plc-doc.readthedocs.io/latest/src/directives.html#autogvl and https://plc-doc.readthedocs.io/latest/src/directives.html#gvl

They look a bit crude still, but they work.
